import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { IncomeStatementsTable } from "@/components"
import { IncomeStatementsResponse } from '@/types'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  const res = await fetch('https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol=IBM&apikey=EF0VRKSNZAUANY5V');
  const data = await res.json();

  if(data) {
    return {
      props: {data}
    }
  }
}

export default function Home(props: IncomeStatementsResponse) {

  const { data } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <IncomeStatementsTable data={data} />
      </main>
    </>
  )
}
